FROM puckel/docker-airflow:1.10.9

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        default-libmysqlclient-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    SQLAlchemy \
    pandas \
    pmdarima \
    statsmodels \
    numpy==1.21.2

ENTRYPOINT ["./entrypoint.sh"]
CMD ["webserver"]
